/* ---------------------------------------------------------------------------
 * Lower-carbon alternatives, generated by a model.
 *
 * WHAT THIS IS AND ISN'T. The model proposes alternative products and says why
 * each is lower-carbon. Those suggestions are model output, not published
 * data, and the card labels them as estimates — never as sourced figures. The
 * one hard rule enforced here: we never hand the UI a product URL the model
 * invented. Links are RETAILER SEARCH URLs built from the suggested name, so
 * every link on the card resolves to a real page.
 *
 * Sourced numbers still come from the Snowflake knowledge base (proxy/
 * guidance.js) and stay clearly separated from anything on this side.
 * ------------------------------------------------------------------------- */

const SYSTEM = `You are a sustainability analyst. Given a product someone is about to buy,
propose up to 3 concrete lower-carbon alternatives they could buy instead.

Prefer, in order:
1. The same product class with materially better use-phase energy (ENERGY STAR
   certified, lower annual kWh, higher efficiency rating).
2. A model from a manufacturer that publishes a product carbon footprint.
3. A more durable or repairable option that needs replacing far less often.
4. A smaller or right-sized version, when the original is oversized for its use.

Rules:
- Name a real, buyable product category and model family. Never invent a model
  number you are not confident exists.
- "why" is ONE sentence naming the actual mechanism (kWh/year, certification,
  lifespan), not a vague claim about being eco-friendly.
- co2SavingKgPerYear: a number ONLY when you can reason it from energy use.
  Otherwise null. Do not guess. A null is a correct answer.
- If the product has no meaningful lower-carbon alternative, return an empty list.

Reply with JSON only: {"alternatives":[{"title":"...","why":"...","co2SavingKgPerYear":null,"searchQuery":"..."}]}`;

/* A spoken request is someone asking for help finding a thing, not someone
 * already holding one — an empty answer leaves them with nothing. So in voice
 * mode there is always at least one pick, and when the category genuinely has
 * few lower-carbon options we say why instead of pretending otherwise. */
const SPOKEN = `

The person asked for this out loud, so they are looking for something to buy.
- ALWAYS return at least 1 item, even if nothing is meaningfully lower-carbon.
- If the category genuinely has few lower-carbon alternatives, set
  "scarcityReason" to ONE plain sentence explaining why for this kind of product
  (for example: most of its footprint is electricity used while running, and
  models differ little). Then return the most efficient or most durable pick in
  the category.
- If there are real lower-carbon options, set "scarcityReason" to null.

Reply with JSON only: {"scarcityReason":null,"alternatives":[{"title":"...","why":"...","co2SavingKgPerYear":null,"searchQuery":"..."}]}`;

const SEARCH_URL = {
  amazon: (q) => `https://www.amazon.com/s?k=${encodeURIComponent(q)}`,
  bestbuy: (q) => `https://www.bestbuy.com/site/searchpage.jsp?st=${encodeURIComponent(q)}`,
};

function searchUrlFor(sourceUrl, query) {
  const host = String(sourceUrl || '');
  if (host.includes('bestbuy')) return SEARCH_URL.bestbuy(query);
  return SEARCH_URL.amazon(query);
}

const NONE = { alternatives: [], scarcityReason: null };

/**
 * @returns {Promise<{alternatives: Array, scarcityReason: string|null}>}
 * Empty when we have no key or the call fails — never a fabricated list.
 */
async function alternativesFor(product, guidance) {
  const key = process.env.OPENAI_API_KEY;
  if (!key) return NONE;

  const prompt = [
    product.spoken
      ? `The person said out loud what they want to buy: "${product.title}". Work out the product they mean first.`
      : `Product: ${product.title}`,
    product.price ? `Price: ${product.currency || 'USD'} ${product.price}` : '',
    guidance ? `Category: ${guidance.category}` : '',
    guidance && guidance.embodiedCo2Kg
      ? `Published manufacturing footprint for this category: ~${guidance.embodiedCo2Kg} kg CO2e`
      : '',
  ]
    .filter(Boolean)
    .join('\n');

  try {
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: { 'content-type': 'application/json', authorization: `Bearer ${key}` },
      body: JSON.stringify({
        model: process.env.OPENAI_MODEL || 'gpt-4o-mini',
        temperature: 0.2,
        response_format: { type: 'json_object' },
        messages: [
          { role: 'system', content: product.spoken ? SYSTEM + SPOKEN : SYSTEM },
          { role: 'user', content: prompt },
        ],
      }),
    });

    if (!response.ok) {
      console.warn(`[verte] alternatives HTTP ${response.status}`);
      return NONE;
    }

    const data = await response.json();
    const parsed = JSON.parse(data.choices?.[0]?.message?.content || '{}');
    const list = Array.isArray(parsed.alternatives) ? parsed.alternatives : [];

    const alternatives = list
      .filter((a) => a && typeof a.title === 'string' && a.title.trim())
      .slice(0, 3)
      .map((a) => {
        const saving = Number(a.co2SavingKgPerYear);
        return {
          source: 'ai',
          title: String(a.title).trim().slice(0, 90),
          why: String(a.why || '').trim().slice(0, 180),
          co2SavingKgPerYear: Number.isFinite(saving) && saving > 0 ? Math.round(saving) : null,
          // A real search on the retailer you're already on — never a made-up
          // product URL that 404s the moment anyone clicks it.
          url: searchUrlFor(product.sourceUrl, a.searchQuery || a.title),
          estimated: true,
        };
      });

    const reason = typeof parsed.scarcityReason === 'string' ? parsed.scarcityReason.trim() : '';
    return {
      alternatives,
      // Only meaningful alongside a pick; a reason with nothing under it is
      // just the empty state again.
      scarcityReason: reason && alternatives.length ? reason.slice(0, 220) : null,
    };
  } catch (error) {
    console.warn(`[verte] alternatives unavailable: ${error.message}`);
    return NONE;
  }
}

module.exports = { alternativesFor };
