/* ---------------------------------------------------------------------------
 * The category knowledge base.
 *
 * Static data, so it ships inside the extension. It used to live behind the
 * proxy, which meant the extension could not say anything about a product
 * unless a localhost server happened to be running — the single reason it
 * worked on one machine and not another.
 *
 * A category carries a carbon figure ONLY when co2Source names a real
 * reference. Where none was found, embodiedCo2Kg is 0 and co2Source is empty,
 * and isSourced() suppresses the claim rather than printing an indefensible
 * number.
 * ------------------------------------------------------------------------- */

import type { CategoryGuidance } from './types'

export const GUIDANCE: Record<string, CategoryGuidance> = {
  /* SOURCED. Published smartphone LCAs consistently put manufacturing at
   * 85-95% of a phone's lifetime footprint, around 55 kg CO2e on average —
   * the strongest used-versus-new case of any category we cover. */
  phone: {
    category: 'phone',
    carbonCase: 'manufacturing',
    verdict: 'check',
    checkTips: [
      'Ask for the battery health percentage.',
      'Confirm it is not carrier-locked or activation-locked.',
      'Check the IMEI is not blacklisted before paying.',
    ],
    embodiedCo2Kg: 55,
    co2Source:
      'Published smartphone LCAs — ~55 kg CO2e manufacturing, 85-95% of lifetime footprint',
    note: 'Manufacturing is almost the entire footprint of a phone, so a used one avoids nearly all of it.',
    bulky: false,
    useDominant: false,
  },
  'pressure-cooker': {
    category: 'pressure-cooker',
    carbonCase: 'manufacturing',
    verdict: 'check',
    checkTips: [
      "Check the lid gasket \u2014 it perishes and is the usual failure.",
      "Confirm the pressure-release valve moves freely.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "The pot outlives several gaskets, and gaskets are cheap.",
    bulky: false,
    useDominant: false,
  },
  'air-fryer': {
    category: 'air-fryer',
    carbonCase: 'manufacturing',
    verdict: 'check',
    checkTips: [
      "Check the basket coating is not flaking.",
      "Run it once to check the fan and thermostat.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "A flaking basket is the one thing worth walking away from.",
    bulky: false,
    useDominant: false,
  },
  toaster: {
    category: 'toaster',
    carbonCase: 'manufacturing',
    verdict: 'safe',
    checkTips: [
      "Shake out the crumb tray and check the element glows evenly.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Almost nothing to go wrong.",
    bulky: false,
    useDominant: false,
  },
  'rice-cooker': {
    category: 'rice-cooker',
    carbonCase: 'manufacturing',
    verdict: 'check',
    checkTips: [
      "Check the inner pot coating for scratches.",
      "Confirm the keep-warm setting still works.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Inner pots can usually be replaced separately.",
    bulky: false,
    useDominant: false,
  },
  vacuum: {
    category: 'vacuum',
    carbonCase: 'manufacturing',
    verdict: 'check',
    checkTips: [
      "Budget for a new filter.",
      "Check the brush bar spins and the hose is not split.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Filters and belts are consumables, not faults.",
    bulky: false,
    useDominant: false,
  },
  humidifier: {
    category: 'humidifier',
    carbonCase: 'manufacturing',
    verdict: 'check',
    checkTips: [
      "Check for limescale and mould in the tank.",
      "Confirm the tank seal does not leak.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Hygiene is the thing to inspect, not the motor.",
    bulky: false,
    useDominant: false,
  },
  lamp: {
    category: 'lamp',
    carbonCase: 'manufacturing',
    verdict: 'safe',
    checkTips: [
      "Check the switch and that the cord is not frayed.",
      "Bulbs are cheap \u2014 a dead bulb is not a dead lamp.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Nothing meaningful degrades. Ideal used.",
    bulky: false,
    useDominant: false,
  },
  mouse: {
    category: 'mouse',
    carbonCase: 'manufacturing',
    verdict: 'check',
    checkTips: [
      "Click every button, including the scroll wheel.",
      "Worn feet are cheap to replace; a failing switch is not.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Switches wear before anything else does.",
    bulky: false,
    useDominant: false,
  },
  keyboard: {
    category: 'keyboard',
    carbonCase: 'manufacturing',
    verdict: 'check',
    checkTips: [
      "Test every key.",
      "Ask whether it has been cleaned \u2014 they collect a lot.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Mechanical keyboards in particular outlast several owners.",
    bulky: false,
    useDominant: false,
  },
  speaker: {
    category: 'speaker',
    carbonCase: 'manufacturing',
    verdict: 'check',
    checkTips: [
      "Play something at volume and listen for rattle.",
      "Check the charging port if it is portable.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Drivers last a long time; batteries do not.",
    bulky: false,
    useDominant: false,
  },
  'coffee-maker': {
    category: 'coffee-maker',
    carbonCase: 'manufacturing',
    verdict: 'check',
    checkTips: [
      "Descale before first use.",
      "Check the carafe and seals for cracks.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Limescale is cosmetic. Cracked seals leak.",
    bulky: false,
    useDominant: false,
  },
  backpack: {
    category: 'backpack',
    carbonCase: 'materials',
    verdict: 'safe',
    checkTips: [
      "Run every zip.",
      "Check the base and strap seams, which fail first.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Excellent used. Straps and zips tell you everything.",
    bulky: false,
    useDominant: false,
  },
  /* Every slug proxy/categories.ts can produce needs an entry here, or the
   * lookup 404s and no card ever appears. Verdicts and tips are real advice;
   * carbon stays 0/'' unless a citation exists (§09). */
  'bike-helmet': {
    category: 'bike-helmet',
    carbonCase: 'materials',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Single-impact protection, and a helmet that has already been dropped looks identical to one that has not.",
    bulky: false,
    useDominant: false,
  },
  'desk-chair': {
    category: 'desk-chair',
    carbonCase: 'materials',
    verdict: 'check',
    checkTips: [
      "Sit on it and check the gas cylinder does not sink.",
      "Test that the recline lock holds.",
    ],
    embodiedCo2Kg: 85,
    co2Source:
      "Herman Miller Aeron Chair Environmental Product Declaration (2016) — 85.3 kg CO2e cradle-to-gate, A1–A3",
    note: "A failed gas cylinder is a real repair, not a quirk.",
    bulky: true,
    useDominant: false,
  },
  'non-stick-pan': {
    category: 'non-stick-pan',
    carbonCase: 'materials',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "The coating degrades and scratches. Buy cast iron or stainless used instead.",
    bulky: false,
    useDominant: false,
  },
  'smoke-detector': {
    category: 'smoke-detector',
    carbonCase: 'materials',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Sensors expire on a fixed schedule from manufacture.",
    bulky: false,
    useDominant: false,
  },
  'surge-protector': {
    category: 'surge-protector',
    carbonCase: 'materials',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Protection components wear out invisibly with every surge absorbed.",
    bulky: false,
    useDominant: false,
  },
  'drying-rack': {
    category: 'drying-rack',
    carbonCase: 'materials',
    verdict: 'safe',
    checkTips: [
      "Confirm the hinges lock open.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Nothing to go wrong. Always worth checking used first.",
    bulky: false,
    useDominant: false,
  },
  'storage-bin': {
    category: 'storage-bin',
    carbonCase: 'minimal',
    verdict: 'safe',
    checkTips: [
      "Check for cracks along the base.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "No meaningful risk. Never buy these new.",
    bulky: false,
    useDominant: false,
  },
  pillow: {
    category: 'pillow',
    carbonCase: 'minimal',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Hygiene, and they are cheap enough new that it does not sting.",
    bulky: false,
    useDominant: false,
  },
  bookshelf: {
    category: 'bookshelf',
    carbonCase: 'materials',
    verdict: 'safe',
    checkTips: [
      "Check the shelves are not sagging.",
      "Confirm the wall anchor hardware is included.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Very little that can go wrong.",
    bulky: true,
    useDominant: false,
  },
  dresser: {
    category: 'dresser',
    carbonCase: 'materials',
    verdict: 'safe',
    checkTips: [
      "Open every drawer.",
      "Check the back panel is still attached.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Heavy, so favour local pickup over shipping.",
    bulky: true,
    useDominant: false,
  },
  microwave: {
    category: 'microwave',
    carbonCase: 'manufacturing',
    verdict: 'safe',
    checkTips: [
      "Check the door latch closes firmly.",
      "The interior should not be scorched or rusted.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "A damaged door seal is the one real safety concern.",
    bulky: false,
    useDominant: false,
  },
  textbook: {
    category: 'textbook',
    carbonCase: 'minimal',
    verdict: 'safe',
    checkTips: [
      "Confirm the edition matches the syllabus.",
      "Ask whether an access code is required and still unused.",
    ],
    embodiedCo2Kg: 3,
    co2Source:
      "Wells et al. 2012, Journal of Industrial Ecology — 2.71 kg CO2e per paperback, cradle-to-gate",
    note: "A previous edition is often fine, and usually a fraction of the price.",
    bulky: false,
    useDominant: false,
  },
  cookware: {
    category: 'cookware',
    carbonCase: 'materials',
    verdict: 'safe',
    checkTips: [
      "Surface rust on cast iron is cosmetic and scrubs off.",
      "Check stainless pans sit flat on a counter.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Cast iron and stainless are effectively indestructible.",
    bulky: false,
    useDominant: false,
  },
  bike: {
    category: 'bike',
    carbonCase: 'materials',
    verdict: 'safe',
    checkTips: [
      "Inspect the frame for cracks near the welds.",
      "Spin both wheels and check they run true.",
      "Chain, brakes and tyres are cheap to replace.",
    ],
    embodiedCo2Kg: 116,
    co2Source:
      "Trek Bicycle 2021 Sustainability Report — Marlin hardtail, 116 kg CO2e per bike manufactured",
    note: "Frame condition is the only thing that really matters.",
    bulky: false,
    useDominant: false,
  },
  fan: {
    category: 'fan',
    carbonCase: 'manufacturing',
    verdict: 'safe',
    checkTips: [
      "Run it on every speed setting.",
      "Check the cage is not bent into the blades.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "No meaningful risk.",
    bulky: false,
    useDominant: false,
  },
  blender: {
    category: 'blender',
    carbonCase: 'manufacturing',
    verdict: 'check',
    checkTips: [
      "Inspect the seal and gasket around the blade assembly.",
      "Cracked plastic near the base means leaks.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Seals perish long before motors do.",
    bulky: false,
    useDominant: false,
  },
  kettle: {
    category: 'kettle',
    carbonCase: 'manufacturing',
    verdict: 'check',
    checkTips: [
      "Limescale is cosmetic and descales off.",
      "Check the flex and plug for fraying.",
      "Confirm the auto shut-off works.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "A failed auto shut-off is the one thing to avoid.",
    bulky: false,
    useDominant: false,
  },
  headphones: {
    category: 'headphones',
    carbonCase: 'manufacturing',
    verdict: 'check',
    checkTips: [
      "Budget for replacement ear pads.",
      "Test both channels before paying.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Hygiene is the reason for the caveat, not whether they work.",
    bulky: false,
    useDominant: false,
  },
  'winter-coat': {
    category: 'winter-coat',
    carbonCase: 'materials',
    verdict: 'check',
    checkTips: [
      "Run every zip fully up and down.",
      "Check the insulation still lofts rather than sitting flat.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Excellent value used. Flattened insulation cannot be restored.",
    bulky: false,
    useDominant: false,
  },
  'mini-fridge': {
    category: 'mini-fridge',
    carbonCase: 'manufacturing',
    verdict: 'safe',
    checkTips: [
      'Check the door seal for cracks or gaps.',
      'Confirm it cools within an hour of plugging in.',
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: 'Compressor appliances last well, but the electricity is the real cost here — a cheap old one is not automatically the greener choice.',
    bulky: true,
    useDominant: true,
  },
  mattress: {
    category: 'mattress',
    carbonCase: 'materials',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: 'Hygiene and pest risk, and compression is permanent. Buy this one new.',
    bulky: true,
    useDominant: false,
  },
  /* SOURCED. Dell publishes a per-product carbon footprint datasheet for the
   * S2421HS 24" monitor: 476 kg CO2e over the full life cycle, of which
   * manufacturing is 67.7% -> ~322 kg. Displays are the strongest case Verte
   * has: the footprint is overwhelmingly in the making, not the using. */
  monitor: {
    category: 'monitor',
    carbonCase: 'manufacturing',
    verdict: 'safe',
    checkTips: [
      'Show a white image and look for dead pixels.',
      'Check the corners for backlight bleed in a dark room.',
      'Confirm which cables are included.',
    ],
    embodiedCo2Kg: 322,
    co2Source: 'Dell S2421HS Monitor PCF datasheet — 476 kg CO2e total, 67.7% manufacturing',
    note: 'Most of a display\'s footprint is in the making of it, so a used one avoids nearly all of it.',
    bulky: false,
    useDominant: false,
  },

  /* SOURCED. Apple's Product Environmental Report for the 13-inch MacBook Air
   * puts life-cycle emissions at ~161 kg CO2e with 76% from production. */
  laptop: {
    category: 'laptop',
    carbonCase: 'manufacturing',
    verdict: 'check',
    checkTips: [
      'Ask for the battery cycle count.',
      'Confirm it powers on and gets past the setup screen.',
      'Check it is not activation locked to the previous owner.',
    ],
    embodiedCo2Kg: 122,
    co2Source: 'Apple 13-inch MacBook Air Product Environmental Report — 161 kg CO2e, 76% production',
    note: 'Production dominates a laptop\'s footprint. Activation lock is the one thing that makes a cheap one worthless.',
    bulky: false,
    useDominant: false,
  },

  desk: {
    category: 'desk',
    carbonCase: 'materials',
    verdict: 'safe',
    checkTips: [
      'Check the drawer runners slide cleanly.',
      "Make sure it isn't particleboard that has been wet.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: 'Ideal used. Solid wood outlives several owners.',
    bulky: true,
    useDominant: false,
  },
  tablet: {
    category: 'tablet',
    carbonCase: 'manufacturing',
    verdict: 'check',
    checkTips: [
      'Confirm it is not activation locked to the previous owner.',
      'Ask for the battery health percentage.',
      'Check it still receives OS updates — old tablets get dropped quietly.',
    ],
    embodiedCo2Kg: 59,
    co2Source:
      'Apple iPad (9th generation) Product Environmental Report — 75 kg CO2e life cycle, 78% production',
    note: 'Production dominates a tablet\u2019s footprint. Activation lock is the one thing that makes a cheap one worthless.',
    bulky: false,
    useDominant: false,
  },
  'game-console': {
    category: 'game-console',
    carbonCase: 'manufacturing',
    verdict: 'check',
    checkTips: [
      'Confirm it is not banned from online play — ask the seller to sign in.',
      'Listen to the fan under load; a screaming fan means dust or dried paste.',
      'Check the storage is wiped, not just logged out.',
    ],
    embodiedCo2Kg: 89,
    co2Source:
      'University of Cambridge study of the PlayStation 4 — ~89 kg CO2e to manufacture and ship one unit',
    note: 'Consoles last a decade and hold value. The risks are an account ban and a neglected fan, both checkable.',
    bulky: false,
    useDominant: false,
  },

  /* --- the rest of a first-year's shopping list -----------------------
   * None of these carry a measured figure and most never will, so each
   * states its case through carbonCase instead: where the emissions
   * sit, which is true by construction and needs no citation.
   *
   * Consumables and hygiene goods are deliberately 'avoid'. Verte
   * telling a student to buy a used toothbrush head or a half-used
   * bottle of detergent would discredit every honest recommendation
   * beside it.
   * ------------------------------------------------------------------ */
  'paper-towel': {
    category: 'paper-towel',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Used up in use. Buy it new \u2014 and buy less of it.",
    bulky: false,
    useDominant: false,
    carbonCase: 'consumable',
  },
  'toilet-paper': {
    category: 'toilet-paper',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Used up in use. Buy it new.",
    bulky: false,
    useDominant: false,
    carbonCase: 'consumable',
  },
  'garbage-bag': {
    category: 'garbage-bag',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Used up in use. Buy it new.",
    bulky: false,
    useDominant: false,
    carbonCase: 'consumable',
  },
  'dish-soap': {
    category: 'dish-soap',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Used up in use. Buy it new.",
    bulky: false,
    useDominant: false,
    carbonCase: 'consumable',
  },
  'laundry-detergent': {
    category: 'laundry-detergent',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Used up in use. Buy it new.",
    bulky: false,
    useDominant: false,
    carbonCase: 'consumable',
  },
  'cleaning-spray': {
    category: 'cleaning-spray',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Used up in use. Buy it new.",
    bulky: false,
    useDominant: false,
    carbonCase: 'consumable',
  },
  sponge: {
    category: 'sponge',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Used up in use, and not something to inherit. Buy it new.",
    bulky: false,
    useDominant: false,
    carbonCase: 'consumable',
  },
  'printer-ink': {
    category: 'printer-ink',
    verdict: 'check',
    checkTips: [
      "Remanufactured cartridges are a real option and genuinely lower impact.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Refilled and remanufactured cartridges avoid a new one being made. Third-party new ones do not.",
    bulky: false,
    useDominant: false,
    carbonCase: 'consumable',
  },
  'printer-paper': {
    category: 'printer-paper',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Used up in use. Recycled-content paper is the choice that matters here.",
    bulky: false,
    useDominant: false,
    carbonCase: 'consumable',
  },
  pen: {
    category: 'pen',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Used up in use. Refillable pens are the choice that matters here.",
    bulky: false,
    useDominant: false,
    carbonCase: 'consumable',
  },
  highlighter: {
    category: 'highlighter',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Used up in use. Buy it new.",
    bulky: false,
    useDominant: false,
    carbonCase: 'consumable',
  },
  'sticky-note': {
    category: 'sticky-note',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Used up in use. Buy it new.",
    bulky: false,
    useDominant: false,
    carbonCase: 'consumable',
  },
  'electric-toothbrush': {
    category: 'electric-toothbrush',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "A used handle cannot be meaningfully sanitised where it matters, around the head seal. Buy this one new.",
    bulky: false,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  shaver: {
    category: 'shaver',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Blades and heads sit against skin. Not something to buy secondhand. Buy this one new.",
    bulky: false,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  towels: {
    category: 'towels',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Hygiene, and they wear out. Buy these new.",
    bulky: false,
    useDominant: false,
    carbonCase: 'materials',
  },
  'bath-mat': {
    category: 'bath-mat',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Hygiene. Buy this one new.",
    bulky: false,
    useDominant: false,
    carbonCase: 'materials',
  },
  bedsheets: {
    category: 'bedsheets',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Hygiene. Buy these new.",
    bulky: false,
    useDominant: false,
    carbonCase: 'materials',
  },
  duvet: {
    category: 'duvet',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Hygiene, and they cannot be properly cleaned between owners. Buy this one new.",
    bulky: true,
    useDominant: false,
    carbonCase: 'materials',
  },
  'mattress-topper': {
    category: 'mattress-topper',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Hygiene and pest risk, and foam compression is permanent. Buy this one new.",
    bulky: true,
    useDominant: false,
    carbonCase: 'materials',
  },
  'toilet-brush': {
    category: 'toilet-brush',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Buy this one new.",
    bulky: false,
    useDominant: false,
    carbonCase: 'minimal',
  },
  'shaker-bottle': {
    category: 'shaker-bottle',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Hygiene. Buy this one new.",
    bulky: false,
    useDominant: false,
    carbonCase: 'minimal',
  },
  'water-bottle': {
    category: 'water-bottle',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "You cannot verify how a bottle was cleaned or what was kept in it, and the seal and straw are where that matters. Buy this one new.",
    bulky: false,
    useDominant: false,
    carbonCase: 'materials',
  },
  'water-filter': {
    category: 'water-filter',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "A filter's job is what it has already absorbed. Buying that history secondhand defeats the point. Buy this one new.",
    bulky: false,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  'bike-lock': {
    category: 'bike-lock',
    verdict: 'avoid',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "A lock you did not buy new is a lock someone else may still have a key to. Buy this one new.",
    bulky: false,
    useDominant: false,
    carbonCase: 'materials',
  },
  tv: {
    category: 'tv',
    verdict: 'check',
    checkTips: [
      "Have it powered on before you commit \u2014 look for lines, dark patches or dead pixels.",
      "Check the panel for pressure marks, which show as clouding on a white screen.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "A panel fault is invisible on a switched-off screen, and it is the only defect that really matters.",
    bulky: true,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  webcam: {
    category: 'webcam',
    verdict: 'safe',
    checkTips: [
      "Plug it in and check the autofocus settles.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Nothing inside wears out, and anything broken shows up the first time you open it.",
    bulky: false,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  router: {
    category: 'router',
    verdict: 'check',
    checkTips: [
      "Check the manufacturer still ships firmware updates for that model.",
      "Factory reset it before use \u2014 never trust an inherited configuration.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "A router with no security updates is a liability on your network, so the model matters more than its age.",
    bulky: false,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  printer: {
    category: 'printer',
    verdict: 'check',
    checkTips: [
      "Price the cartridges before you buy \u2014 they often cost more than the printer.",
      "Print a test page; a clogged inkjet head is usually unfixable.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "The purchase price is the small part. A cheap used inkjet with clogged heads is no bargain.",
    bulky: true,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  'external-drive': {
    category: 'external-drive',
    verdict: 'check',
    checkTips: [
      "Ask for the SMART power-on hours before you buy.",
      "Run a full read test on arrival, while you can still return it.",
      "Never keep your only copy of anything on a used drive.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Enclosures last, but a drive's remaining life is the whole question \u2014 and SMART data answers it honestly.",
    bulky: false,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  charger: {
    category: 'charger',
    verdict: 'check',
    checkTips: [
      "Use the manufacturer’s own, or a known brand \u2014 cheap third-party chargers are a genuine fire risk.",
      "Check the cable where it meets the brick for kinks.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "A first-party charger outlives several laptops. An unbranded one is the wrong thing to save money on.",
    bulky: false,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  cable: {
    category: 'cable',
    verdict: 'safe',
    checkTips: [
      "Check both ends for bent pins and the jacket for kinks.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Cables are the easiest win there is. They do not wear out, and everyone has spares.",
    bulky: false,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  'usb-hub': {
    category: 'usb-hub',
    verdict: 'safe',
    checkTips: [
      "Plug something into every port before the return window closes.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Passive electronics with nothing to wear out. An obvious used buy.",
    bulky: false,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  'extension-cord': {
    category: 'extension-cord',
    verdict: 'check',
    checkTips: [
      "Check the whole length of the cable for nicks, and the plug for scorching.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Fine used if the cable is intact. Anything scorched or frayed goes in the bin, not your room.",
    bulky: false,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  controller: {
    category: 'controller',
    verdict: 'check',
    checkTips: [
      "Test both sticks in a drift checker before the return window closes.",
      "Press every face and shoulder button \u2014 worn switches feel mushy.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Stick drift is the one failure that makes a cheap controller worthless, and it takes a minute to test.",
    bulky: false,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  'streaming-stick': {
    category: 'streaming-stick',
    verdict: 'check',
    checkTips: [
      "Factory reset it so it is off the previous owner’s account.",
      "Check the model still gets app updates \u2014 old sticks lose Netflix quietly.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "The hardware is fine. What dates these is app support, so the model year matters more than condition.",
    bulky: false,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  'desktop-pc': {
    category: 'desktop-pc',
    verdict: 'check',
    checkTips: [
      "Ask what the parts are, not just the badge \u2014 a used prebuilt is only as good as its GPU and PSU.",
      "Listen to the fans under load and check the vents for dust.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "The single strongest secondhand buy in tech: components far outlive one owner, and a tower is built to be opened.",
    bulky: true,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  'pc-part': {
    category: 'pc-part',
    verdict: 'check',
    checkTips: [
      "Ask whether it was used for mining or overclocked.",
      "Stress test it while you can still return it.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Components are designed to be swapped and reused. This is what the secondhand market is best at.",
    bulky: false,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  'alarm-clock': {
    category: 'alarm-clock',
    verdict: 'safe',
    checkTips: [
      "Check the display has no dead segments.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Almost nothing to go wrong, and they long outlast one owner.",
    bulky: false,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  'led-strip': {
    category: 'led-strip',
    verdict: 'check',
    checkTips: [
      "Power the whole run \u2014 dead segments do not show until it is lit.",
      "Check the adhesive backing is still usable, or budget for clips.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "LEDs last tens of thousands of hours. The adhesive gives out long before the light does.",
    bulky: false,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  calculator: {
    category: 'calculator',
    verdict: 'safe',
    checkTips: [
      "Check every key registers and the screen has no dead segments.",
      "Confirm the model is allowed in your exams.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "A graphing calculator outlives a degree several times over. Buying one new is close to pointless.",
    bulky: false,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  'space-heater': {
    category: 'space-heater',
    verdict: 'check',
    checkTips: [
      "Check the cord and plug for scorching, and that the tip-over cutout works.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Running one costs far more carbon than making one. Check the wattage before the price.",
    bulky: true,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  'air-purifier': {
    category: 'air-purifier',
    verdict: 'check',
    checkTips: [
      "Price a replacement filter \u2014 assume you need one immediately.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "The machine is fine used. Always budget a new filter on day one; the old one is not worth inheriting.",
    bulky: true,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  'hair-dryer': {
    category: 'hair-dryer',
    verdict: 'check',
    checkTips: [
      "Run it on every heat setting and smell for burning.",
      "Check the cord where it meets the body for kinks.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Motors and elements last well. A frayed cord is the one fault worth walking away from.",
    bulky: false,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  'bathroom-scale': {
    category: 'bathroom-scale',
    verdict: 'safe',
    checkTips: [
      "Stand on it twice and check it repeats.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Nothing wears out. An obvious used buy.",
    bulky: false,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  'sandwich-maker': {
    category: 'sandwich-maker',
    verdict: 'check',
    checkTips: [
      "Check the plates are not scratched through the coating.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Fine used if the coating is intact. A scratched non-stick plate is the reason to pass.",
    bulky: false,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  'bedside-table': {
    category: 'bedside-table',
    verdict: 'safe',
    checkTips: [
      "Check the drawer runners slide cleanly.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Furniture is the easiest secondhand win there is. Nothing that matters wears out.",
    bulky: true,
    useDominant: false,
    carbonCase: 'materials',
  },
  'storage-shelf': {
    category: 'storage-shelf',
    verdict: 'safe',
    checkTips: [
      "Confirm all the fixings are there \u2014 they rarely are.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Steel shelving outlives several owners. Buying one new is close to pure waste.",
    bulky: true,
    useDominant: false,
    carbonCase: 'materials',
  },
  'drawer-organizer': {
    category: 'drawer-organizer',
    verdict: 'safe',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Small, light, and indestructible. Used is fine; so is doing without.",
    bulky: false,
    useDominant: false,
    carbonCase: 'minimal',
  },
  'under-bed-storage': {
    category: 'under-bed-storage',
    verdict: 'safe',
    checkTips: [
      "Check the wheels and the lid seal.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Plastic storage lasts decades. There is no reason for this to be new.",
    bulky: true,
    useDominant: false,
    carbonCase: 'materials',
  },
  hangers: {
    category: 'hangers',
    verdict: 'safe',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Nobody should buy these new. Every move leaves a pile of them behind.",
    bulky: false,
    useDominant: false,
    carbonCase: 'minimal',
  },
  'laundry-hamper': {
    category: 'laundry-hamper',
    verdict: 'safe',
    checkTips: [
      "Check the frame and the seams if it folds.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Nothing to wear out. An obvious used buy.",
    bulky: true,
    useDominant: false,
    carbonCase: 'materials',
  },
  'shoe-rack': {
    category: 'shoe-rack',
    verdict: 'safe',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Furniture with nothing to wear out. Used is the sensible default.",
    bulky: true,
    useDominant: false,
    carbonCase: 'materials',
  },
  mirror: {
    category: 'mirror',
    verdict: 'check',
    checkTips: [
      "Check the backing for black spots, which spread and cannot be fixed.",
      "Confirm the fixings are included if it hangs.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Glass does not age. Desilvering at the edges is the one thing to look for.",
    bulky: true,
    useDominant: false,
    carbonCase: 'materials',
  },
  curtains: {
    category: 'curtains',
    verdict: 'check',
    checkTips: [
      "Measure your window first \u2014 this is the usual reason they end up resold.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Textiles launder. The reason these are resold is almost always that they were the wrong size.",
    bulky: false,
    useDominant: false,
    carbonCase: 'materials',
  },
  'curtain-rod': {
    category: 'curtain-rod',
    verdict: 'safe',
    checkTips: [
      "Confirm the brackets and screws are included.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "A metal pole. There is nothing here that can wear out.",
    bulky: true,
    useDominant: false,
    carbonCase: 'materials',
  },
  rug: {
    category: 'rug',
    verdict: 'check',
    checkTips: [
      "Ask whether it has been in a home with pets or smokers.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Rugs clean up well and last decades. Worth asking what it has lived with.",
    bulky: true,
    useDominant: false,
    carbonCase: 'materials',
  },
  blanket: {
    category: 'blanket',
    verdict: 'check',
    checkTips: [
      "Wash it before use.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Washable, so unlike bedding this is a reasonable used buy.",
    bulky: false,
    useDominant: false,
    carbonCase: 'materials',
  },
  luggage: {
    category: 'luggage',
    verdict: 'safe',
    checkTips: [
      "Roll it \u2014 wheels and bearings are what wear out.",
      "Extend and retract the handle a few times.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "A hard case survives far more trips than one owner takes. Wheels and handles are the only wear points.",
    bulky: true,
    useDominant: false,
    carbonCase: 'materials',
  },
  'gym-bag': {
    category: 'gym-bag',
    verdict: 'check',
    checkTips: [
      "Run every zip end to end.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Bags are built for abuse and everything that fails is visible from the outside.",
    bulky: false,
    useDominant: false,
    carbonCase: 'materials',
  },
  umbrella: {
    category: 'umbrella',
    verdict: 'safe',
    checkTips: [
      "Open and close it fully \u2014 the ribs are what break.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Nothing to wear out but the ribs, and those you can test in two seconds.",
    bulky: false,
    useDominant: false,
    carbonCase: 'materials',
  },
  'shopping-bag': {
    category: 'shopping-bag',
    verdict: 'safe',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "The greenest tote is the one you already own. Buying a new one defeats the entire point.",
    bulky: false,
    useDominant: false,
    carbonCase: 'minimal',
  },
  'phone-case': {
    category: 'phone-case',
    verdict: 'check',
    checkTips: [
      "Check the corners, which is where a dropped case gives out.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Cheap to make and cheap to buy, so the carbon case is weak \u2014 but a used one is perfectly serviceable.",
    bulky: false,
    useDominant: false,
    carbonCase: 'minimal',
  },
  wallet: {
    category: 'wallet',
    verdict: 'safe',
    checkTips: [
      "Check the stitching and the card slots for stretch.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Leather and canvas outlive several owners, and a used one is already broken in.",
    bulky: false,
    useDominant: false,
    carbonCase: 'materials',
  },
  mug: {
    category: 'mug',
    verdict: 'safe',
    checkTips: [
      "Check the rim and handle for chips.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Ceramic is effectively permanent. There is no reason for a mug to be new.",
    bulky: false,
    useDominant: false,
    carbonCase: 'materials',
  },
  tableware: {
    category: 'tableware',
    verdict: 'safe',
    checkTips: [
      "Check rims for chips, which is where they fail.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Ceramic and glass do not degrade. Student kitchens are furnished entirely from other people’s leftovers.",
    bulky: false,
    useDominant: false,
    carbonCase: 'materials',
  },
  cutlery: {
    category: 'cutlery',
    verdict: 'safe',
    checkTips: [
      "Stainless steel washes clean; check for pitting.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Stainless steel is effectively indestructible. An obvious used buy.",
    bulky: false,
    useDominant: false,
    carbonCase: 'materials',
  },
  'food-container': {
    category: 'food-container',
    verdict: 'check',
    checkTips: [
      "Check lids still seal and the plastic is not stained or cracked.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Fine used if the seals are intact. Cracked plastic is the reason to pass.",
    bulky: false,
    useDominant: false,
    carbonCase: 'materials',
  },
  'baking-tray': {
    category: 'baking-tray',
    verdict: 'safe',
    checkTips: [
      "Surface marking is cosmetic; warping is not.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Steel bakeware improves with age. Buying it new is the worse option.",
    bulky: false,
    useDominant: false,
    carbonCase: 'materials',
  },
  'cutting-board': {
    category: 'cutting-board',
    verdict: 'check',
    checkTips: [
      "Deep knife scoring holds bacteria \u2014 pass on a heavily scored board.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Wood and plastic both last years. How scored it is tells you everything.",
    bulky: false,
    useDominant: false,
    carbonCase: 'materials',
  },
  knife: {
    category: 'knife',
    verdict: 'check',
    checkTips: [
      "Check the edge is not chipped \u2014 dull is fixable, chipped is not.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "A good knife is sharpened, not replaced. Used is how most cooks buy them.",
    bulky: false,
    useDominant: false,
    carbonCase: 'materials',
  },
  'kitchen-tool': {
    category: 'kitchen-tool',
    verdict: 'safe',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Small, cheap and indestructible. Used is fine, and these turn up free constantly.",
    bulky: false,
    useDominant: false,
    carbonCase: 'minimal',
  },
  'dish-rack': {
    category: 'dish-rack',
    verdict: 'safe',
    checkTips: [
      "Check for rust at the joints.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Nothing to wear out but the coating. An obvious used buy.",
    bulky: false,
    useDominant: false,
    carbonCase: 'materials',
  },
  mop: {
    category: 'mop',
    verdict: 'check',
    checkTips: [
      "Replaceable heads are the whole point \u2014 check the head still comes off.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "The handle lasts forever. Buy a new head, not a new mop.",
    bulky: false,
    useDominant: false,
    carbonCase: 'materials',
  },
  'microfiber-cloth': {
    category: 'microfiber-cloth',
    verdict: 'check',
    checkTips: [
      "Wash before use.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Washable and long-lived, but cheap enough that the carbon case is weak either way.",
    bulky: false,
    useDominant: false,
    carbonCase: 'minimal',
  },
  iron: {
    category: 'iron',
    verdict: 'check',
    checkTips: [
      "Check the soleplate for scale and scorching.",
      "Run it once with water to confirm it steams and does not leak.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Scale is what kills these, and you can see it on the soleplate before you buy.",
    bulky: false,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  'ironing-board': {
    category: 'ironing-board',
    verdict: 'safe',
    checkTips: [
      "Check the legs lock and the cover is intact.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "A metal frame with a cover. Nothing here justifies buying new.",
    bulky: true,
    useDominant: false,
    carbonCase: 'materials',
  },
  'sewing-kit': {
    category: 'sewing-kit',
    verdict: 'safe',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "The most useful thing on this list for making everything else last longer.",
    bulky: false,
    useDominant: false,
    carbonCase: 'minimal',
  },
  notebook: {
    category: 'notebook',
    verdict: 'check',
    checkTips: [
      "Check how many pages are actually unused.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Barely any footprint either way. Recycled-content paper is the choice that matters here.",
    bulky: false,
    useDominant: false,
    carbonCase: 'minimal',
  },
  binder: {
    category: 'binder',
    verdict: 'safe',
    checkTips: [],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "These outlast a degree and pile up in every office. Never buy these new.",
    bulky: false,
    useDominant: false,
    carbonCase: 'minimal',
  },
  whiteboard: {
    category: 'whiteboard',
    verdict: 'check',
    checkTips: [
      "Check for ghosting \u2014 old marker that no longer wipes off.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "The board lasts for years. Ghosting is the only thing that ends one.",
    bulky: true,
    useDominant: false,
    carbonCase: 'materials',
  },
  'yoga-mat': {
    category: 'yoga-mat',
    verdict: 'check',
    checkTips: [
      "Check it is not flaking, and clean it before use.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Fine used if the surface is intact. Flaking foam is the reason to pass.",
    bulky: false,
    useDominant: false,
    carbonCase: 'materials',
  },
  weights: {
    category: 'weights',
    verdict: 'safe',
    checkTips: [
      "Check adjustable dumbbells lock at every setting.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Cast iron is the strongest secondhand case there is. It does not wear out, and new ones cost a fortune to ship.",
    bulky: true,
    useDominant: false,
    carbonCase: 'materials',
  },
  'resistance-band': {
    category: 'resistance-band',
    verdict: 'check',
    checkTips: [
      "Stretch a band fully and look for cracking \u2014 perished rubber snaps.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Bars and rollers last forever. Bands perish, so check them before you trust one.",
    bulky: false,
    useDominant: false,
    carbonCase: 'materials',
  },
  'shower-caddy': {
    category: 'shower-caddy',
    verdict: 'safe',
    checkTips: [
      "Check for rust if it is wire.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Small and cheap either way, but there is no reason for one to be new.",
    bulky: false,
    useDominant: false,
    carbonCase: 'minimal',
  },
  "smartwatch": {
    category: 'smartwatch',
    verdict: 'check',
    checkTips: [
      "Confirm it is unpaired and removed from the previous owner\u2019s account.",
      "Ask for battery life in real terms \u2014 these degrade fast.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Account locks and tired batteries are the two things that turn a cheap tracker into a paperweight.",
    bulky: false,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  "microphone": {
    category: 'microphone',
    verdict: 'safe',
    checkTips: [
      "Record a test clip and listen for crackle on the capsule.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Microphones are famously durable \u2014 studios run the same ones for decades.",
    bulky: false,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  "camera": {
    category: 'camera',
    verdict: 'check',
    checkTips: [
      "Ask for the shutter count \u2014 it is a camera\u2019s odometer.",
      "Shoot a plain bright surface and look for sensor dust.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Bodies are built for far more actuations than most owners ever use, so a low shutter count is a genuinely good buy.",
    bulky: false,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  "smart-home": {
    category: 'smart-home',
    verdict: 'check',
    checkTips: [
      "Confirm it has been removed from the previous owner\u2019s account \u2014 many are useless until it is.",
      "Check the model still receives security updates.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "The one thing that bricks these is an account the seller forgot to release, and it is free to check before you pay.",
    bulky: false,
    useDominant: false,
    carbonCase: 'manufacturing',
  },
  "sunglasses": {
    category: 'sunglasses',
    verdict: 'check',
    checkTips: [
      "Hold the lenses to the light at an angle to find scratches.",
      "Check the hinges are tight and the frame is not sprung.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Frames outlive lenses. A scratched or relensed pair may no longer block what it claims to.",
    bulky: false,
    useDominant: false,
    carbonCase: 'materials',
  },
  "shoes": {
    category: 'shoes',
    verdict: 'check',
    checkTips: [
      "Look at the sole tread and the midsole for compression creases.",
      "Running shoes lose cushioning well before they look worn out.",
    ],
    embodiedCo2Kg: 0,
    co2Source: '',
    note: "Fine for casual and fashion pairs. For running, worn midsoles are a genuine injury risk however good they look.",
    bulky: false,
    useDominant: false,
    carbonCase: 'materials',
  },
}

/** Null when we could not classify the product — a normal outcome, not an error. */
export function guidanceFor(category: string | null): CategoryGuidance | null {
  if (!category) return null
  return GUIDANCE[category] ?? null
}
